# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ibus-typing-booster
email: Mike FABIAN <mfabian@redhat.com>
description: > # this means to ignore newlines until "baseurl:"
  Ibus-typing-booster is a completion input method
  for faster typing.
baseurl: "/ibus-typing-booster" # the subpath of your site, e.g. /blog
url: "https://mike-fabian.github.io" # the base hostname & protocol for your site
# twitter_username: mfabian1963
github_username:  mike-fabian

# Build settings
markdown: kramdown
